[package]
name = "turbo_ir"
version = "0.1.0"
authors = ["addrianyy <adrianvpl@gmail.com>"]
edition = "2018"

[dependencies]
asm = { git = "https://github.com/addrianyy/assembler" }
smallvec = "1.5.0"

[features]
self_profile = []
