[package]
name = "brainfuck"
version = "0.1.0"
authors = ["addrianyy <adrianvpl@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies.turbo_ir]
path = "../turbo_ir"
#features = ["self_profile"]
